# Generated by Django 4.0.6 on 2022-08-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_letter_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
