# Generated by Django 4.1 on 2022-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_alter_letter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='audience',
            field=models.CharField(choices=[('public, but as anon', 'Public'), ('private', 'Private')], max_length=20),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(),
        ),
    ]
