# Generated by Django 4.1 on 2022-08-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_letter_delivered_alter_letter_audience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ('-date_posted',)},
        ),
    ]
