# Generated by Django 4.1.5 on 2023-02-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_alter_letter_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='date',
            new_name='delivery_date',
        ),
    ]
