# Generated by Django 4.1.5 on 2023-02-01 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_rename_date_letter_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
