# Generated by Django 4.1.5 on 2023-02-01 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_alter_letter_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
