# Generated by Django 4.1.5 on 2023-02-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_alter_letter_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='message',
            new_name='letter',
        ),
    ]
