# Generated by Django 4.1.5 on 2023-04-02 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("letter", "0010_rename_message_letter_letter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="letter",
            old_name="letter",
            new_name="content",
        ),
    ]
