# Generated by Django 4.1.5 on 2023-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="example.jpg", upload_to="media/blog/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
